package memontago

var ChTrans map[string]string
var EnTrans map[string]string

func initChTrans() map[string]string {
	return map[string]string{
		"justNow":   "刚刚",
		"online":    "在线",
		"ago":       "前",
		"later":     "后",
		"seconds":   "秒",
		"minutes":   "分钟",
		"hours":     "小时",
		"days":      "天",
		"weeks":     "周",
		"months":    "月",
		"years":     "年",
		"Monday":    "星期一",
		"Tuesday":   "星期二",
		"Wednesday": "星期三",
		"Thursday":  "星期四",
		"Friday":    "星期五",
		"Saturday":  "星期六",
		"Sunday":    "星期日"}
} // 在配置的时候调用
func initEnTrans() map[string]string {
	return map[string]string{
		"justNow": "Just now",
		"online":  "Online",
		"ago":     "ago",
		"later":   "later",
		"second":  "second",
		"seconds": "seconds",
		"minute":  "minute",
		"minutes": "minutes",
		"hour":    "hour",
		"hours":   "hours",
		"day":     "day",
		"days":    "days",
		"week":    "week",
		"weeks":   "weeks",
		"month":   "month",
		"months":  "months",
		"year":    "year",
		"years":   "years",
	}
} // 在默认初始化配置的时候调用

var monthMap = map[string]string{
	"01": "1月",
	"02": "2月",
	"03": "3月",
	"04": "4月",
	"05": "5月",
	"06": "6月",
	"07": "7月",
	"08": "8月",
	"09": "9月",
	"10": "10月",
	"11": "11月",
	"12": "12月",
}
var dayMap = map[string]string{
	"01": "1日",
	"02": "2日",
	"03": "3日",
	"04": "4日",
	"05": "5日",
	"06": "6日",
	"07": "7日",
	"08": "8日",
	"09": "9日",
	"10": "10日",
	"11": "11日",
	"12": "12日",
	"13": "13日",
	"14": "14日",
	"15": "15日",
	"16": "16日",
	"17": "17日",
	"18": "18日",
	"19": "19日",
	"20": "20日",
	"21": "21日",
	"22": "22日",
	"23": "23日",
	"24": "24日",
	"25": "25日",
	"26": "26日",
	"27": "27日",
	"28": "28日",
	"29": "29日",
	"30": "30日",
	"31": "31日",
}
